// <auto-generated />
namespace WebAppForYouTubeDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class qtyfieldadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(qtyfieldadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201907021534136_qty field added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
